const http = require('http');
const fs = require('fs');
const path = require('path');

const PORT = process.env.PORT || 3011;
const SITE_URL = process.env.SITE_URL || 'https://2026newhorticultureecommerce.pages.dev';
const DATA_DIR = process.env.DATA_DIR || path.join(__dirname, 'data');
const LOG_FILE = path.join(DATA_DIR, 'pageviews.jsonl');
fs.mkdirSync(DATA_DIR, { recursive: true });

const KEYWORDS = ['flower supply chain','smart flower supply chain','horticulture ecommerce','garden plant marketplace','map flower shopping','wholesale flower auction','reverse flower auction','green certification carbon credit trees','花卉供应链','花卉电商平台','园艺电商','苗木批发拍卖','绿植碳汇认证'];

function send(res, code, obj, headers={}) { const body = typeof obj === 'string' ? obj : JSON.stringify(obj); res.writeHead(code, { 'content-type': typeof obj === 'string' ? 'text/html; charset=utf-8' : 'application/json; charset=utf-8', 'access-control-allow-origin': '*', 'access-control-allow-methods': 'GET,POST,OPTIONS', 'access-control-allow-headers': 'content-type', ...headers }); res.end(body); }
function jsonLine(obj) { fs.appendFile(LOG_FILE, JSON.stringify(obj) + '\n', () => {}); }
function readLines(max = 50000) { if (!fs.existsSync(LOG_FILE)) return []; const txt = fs.readFileSync(LOG_FILE, 'utf8'); return txt.trim().split('\n').filter(Boolean).slice(-max).map(l => { try { return JSON.parse(l); } catch { return null; } }).filter(Boolean); }
function bodyJson(req) { return new Promise(resolve => { let data=''; req.on('data', c => data += c); req.on('end', () => { try { resolve(JSON.parse(data || '{}')); } catch { resolve({}); } }); }); }
function dayOf(ts) { return new Date(ts).toISOString().slice(0, 10); }
function safeUrl(u) { try { return new URL(u).toString(); } catch { return SITE_URL; } }
async function fetchText(url, timeoutMs = 12000) { const ctrl = new AbortController(); const id = setTimeout(() => ctrl.abort(), timeoutMs); try { const res = await fetch(url, { signal: ctrl.signal, headers: { 'user-agent': 'Mozilla/5.0 SEOService/1.0' } }); const text = await res.text(); return { ok: res.ok, status: res.status, text, headers: Object.fromEntries(res.headers.entries()) }; } finally { clearTimeout(id); } }
function extract(html, re) { const m = html.match(re); return m ? m[1].trim().replace(/\s+/g, ' ') : ''; }
function count(re, s) { return (s.match(re) || []).length; }
function safeRef(r) { try { return new URL(r).hostname; } catch { return String(r).slice(0,80); } }
function top(obj) { return Object.entries(obj).sort((a,b)=>b[1]-a[1]).slice(0,10).map(([name,value])=>({name,value})); }
function buildRecommendations(x) { const out=[]; if (!x.title || x.title.length < 15 || x.title.length > 70) out.push('首页 title 控制在 15-70 字符，包含核心关键词。'); if (!x.desc || x.desc.length < 70 || x.desc.length > 170) out.push('description 控制在 70-170 字符，写清业务和地域。'); if (!x.canonical) out.push('增加 canonical，避免重复收录。'); if (!x.ogTitle) out.push('增加 OpenGraph/Twitter Card，提升分享点击率。'); if (!x.jsonLdCount) out.push('增加 JSON-LD 结构化数据：Organization、WebSite、ItemList。'); if (x.h1Count !== 1) out.push('每个页面保持一个明确 H1。'); if (x.imgWithoutAlt > 0) out.push(`有 ${x.imgWithoutAlt} 张图片缺 alt。`); if (!x.robotsOk) out.push('补 robots.txt。'); if (!x.sitemapOk) out.push('补 sitemap.xml 并提交搜索引擎。'); return out; }

async function handle(req, res) {
  if (req.method === 'OPTIONS') return send(res, 204, '');
  const url = new URL(req.url, `http://${req.headers.host || 'localhost'}`);
  try {
    if (url.pathname === '/' || url.pathname === '/index.html') return send(res, 200, '<!doctype html><meta charset="utf-8"><title>SEO Service</title><body style="font-family:system-ui;padding:40px"><h1>SEO Service</h1><p>API: <a href="/api/health">/api/health</a> · <a href="/api/seo/audit">/api/seo/audit</a> · <a href="/api/seo/rankings">/api/seo/rankings</a> · <a href="/api/analytics/summary">/api/analytics/summary</a></p></body>');
    if (url.pathname === '/api/health') return send(res, 200, { status: 'ok', service: 'seo-service', site: SITE_URL, time: new Date().toISOString() });
    if (url.pathname === '/api/track' && req.method === 'POST') { const b = await bodyJson(req); const ip = (req.headers['cf-connecting-ip'] || req.headers['x-forwarded-for'] || req.socket.remoteAddress || '').toString().split(',')[0]; jsonLine({ ts: new Date().toISOString(), path: String(b.path || '/').slice(0,300), referrer: String(b.referrer || '').slice(0,500), title: String(b.title || '').slice(0,200), lang: String(b.lang || '').slice(0,20), screen: String(b.screen || '').slice(0,50), ua: String(req.headers['user-agent'] || '').slice(0,300), ipHash: Buffer.from(ip).toString('base64').slice(0,16) }); return send(res, 200, { ok: true }); }
    if (url.pathname === '/api/analytics/summary') { const lines=readLines(); const sinceDays=Number(url.searchParams.get('days') || 30); const since=Date.now()-sinceDays*86400000; const recent=lines.filter(x=>Date.parse(x.ts)>=since); const byDay={}, byPath={}, byReferrer={}, byLang={}; const visitors=new Set(); for (const x of recent) { byDay[dayOf(x.ts)] = (byDay[dayOf(x.ts)] || 0) + 1; byPath[x.path || '/']=(byPath[x.path || '/']||0)+1; const ref=x.referrer?safeRef(x.referrer):'direct'; byReferrer[ref]=(byReferrer[ref]||0)+1; if(x.lang) byLang[x.lang]=(byLang[x.lang]||0)+1; if(x.ipHash) visitors.add(x.ipHash); } return send(res, 200, { days: sinceDays, pageviews: recent.length, estimatedVisitors: visitors.size, byDay, topPages: top(byPath), topReferrers: top(byReferrer), languages: top(byLang), note: '统计从 seo-service 上线后开始；历史 Cloudflare/Google 数据需要配置对应 API Token。' }); }
    if (url.pathname === '/api/seo/audit') { const target=safeUrl(url.searchParams.get('url') || SITE_URL); const [home,robots,sitemap]=await Promise.allSettled([fetchText(target), fetchText(new URL('/robots.txt', target).toString(),6000), fetchText(new URL('/sitemap.xml', target).toString(),6000)]); const h=home.value?.text || ''; const title=extract(h, /<title[^>]*>([\s\S]*?)<\/title>/i); const desc=extract(h, /<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)["']/i) || extract(h, /<meta[^>]+content=["']([^"']*)["'][^>]+name=["']description["']/i); const canonical=extract(h, /<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']*)["']/i); const ogTitle=extract(h, /<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']*)["']/i); const jsonLdCount=count(/<script[^>]+type=["']application\/ld\+json["']/gi,h); const h1Count=count(/<h1[\s>]/gi,h); const imgWithoutAlt=count(/<img(?![^>]*\balt=)[^>]*>/gi,h); const scoreParts=[title.length>=15&&title.length<=70, desc.length>=70&&desc.length<=170, !!canonical, !!ogTitle, jsonLdCount>0, h1Count===1, robots.value?.ok, sitemap.value?.ok]; const score=Math.round(scoreParts.filter(Boolean).length/scoreParts.length*100); return send(res, 200, { target, checkedAt: new Date().toISOString(), score, status: home.value?.status || 0, title, description: desc, canonical, ogTitle, jsonLdCount, h1Count, imgWithoutAlt, robots: { ok: !!robots.value?.ok, status: robots.value?.status || 0 }, sitemap: { ok: !!sitemap.value?.ok, status: sitemap.value?.status || 0 }, recommendations: buildRecommendations({ title, desc, canonical, ogTitle, jsonLdCount, h1Count, imgWithoutAlt, robotsOk: robots.value?.ok, sitemapOk: sitemap.value?.ok }) }); }
    if (url.pathname === '/api/seo/rankings') { const keywords=String(url.searchParams.get('keywords') || KEYWORDS.join('\n')).split(/[\n,，]+/).map(s=>s.trim()).filter(Boolean).slice(0,20); const domain=new URL(SITE_URL).hostname; const results=[]; for (const keyword of keywords) { const searchUrl='https://www.bing.com/search?q='+encodeURIComponent(keyword)+'&count=20'; try { const {text}=await fetchText(searchUrl,8000); const urls=[...text.matchAll(/<a href="(https?:\/\/[^"#]+)"/g)].map(m=>m[1]).filter(u=>!u.includes('bing.com')); const pos=urls.findIndex(u=>{ try { return new URL(u).hostname.includes(domain); } catch { return false; } }); results.push({ keyword, engine:'bing', rank: pos>=0?pos+1:null, found:pos>=0, checkedAt:new Date().toISOString() }); } catch(e) { results.push({ keyword, engine:'bing', rank:null, found:false, error:e.name==='AbortError'?'timeout':e.message, checkedAt:new Date().toISOString() }); } } return send(res, 200, { site:SITE_URL, domain, results, note:'公开搜索结果会因地区/个性化波动；准确排名建议接入 Google Search Console / Bing Webmaster Tools API。' }); }
    if (url.pathname === '/api/seo/keywords') return send(res, 200, { keywords: KEYWORDS });
    return send(res, 404, { error: 'not found' });
  } catch (e) { return send(res, 500, { error: e.message }); }
}
http.createServer(handle).listen(PORT, '0.0.0.0', () => console.log(`SEO service listening on ${PORT}, site=${SITE_URL}`));
