---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealer-map
  namespace: new-ecommerce
  labels:
    app: dealer-map
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dealer-map
  template:
    metadata:
      labels:
        app: dealer-map
    spec:
      nodeSelector:
        kubernetes.io/hostname: ubuntu-master
      containers:
      - name: dealer-map
        image: 100.76.15.64:5001/dealer-map:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: NODE_ENV
          value: production
---
apiVersion: v1
kind: Service
metadata:
  name: dealer-map
  namespace: new-ecommerce
spec:
  type: NodePort
  selector:
    app: dealer-map
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31308

